Various minute improvements
OpenAttackDefenseTools/tulip pull request #30
Opened 2023-10-24 23:02 UTC by lea-weissman

As the title states.

2023-10-29 21:54 UTC, monoidic commented
LGTM

2023-10-29 22:17 UTC, Diniboy1123 commented on services/flow2pwn.py
LGTM, but next time don't forget to adjust the Copyright statement

2023-10-29 22:19 UTC, monoidic approved these changes

2023-10-29 22:35 UTC, rebane2001 commented on services/flow2pwn.py
> +        if finder := match(b'bd-executor: (.{50})', data):
LGTM, +1 for the 50 character limit to prevent DoS

2023-10-29 22:41 UTC, Speedy11CZ commented on services/flow2pwn.py
> +        if finder := match(b'bd-executor: (.{50})', data):
meme

2023-10-29 22:44 UTC, DaClemens requested changes
Thank you for your first contribution!

I do feel however that your patch is lacking a little bit of documentation. Coukd you explain what bug you're trying to fix, and how you observed this bug? We at the Tulip Development Sweatshop really take feedback seriously, so unfortunately we can't accept patches that don't have any feedback attached with them.

Also, if you have the time, please take a look at #17, it looks to me like these are probably related.

Ping me once you got that covered, and I'll gladly merge!

2023-10-30 11:17 UTC, RickdeJager commented
Nice try ;)

2023-10-30 11:17 UTC, closed without merging